version: '3.8'
services:
  test-db:
    image: postgres:14.5-alpine
    container_name: sublizz-nest-test-db
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sublizz-test
